apiVersion: v1
kind: Secret
metadata:
    name: powergslb-secret
type: Opaque
stringData:
    mariadb-password: ENC[AES256_GCM,data:nF8Zj875rJ9KsM4I8A==,iv:vggAaDkTiGRLoJni7uWJG+V9Co1IQFnWQtDm83eOfEE=,tag:uZgH8gpOsfns1lGUbpF4Pw==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:uM/3GcmQcG7eIlnhaQ==,iv:LrNJC6wa0Hu3ugxhji0/KCh1P9Vx07gpN22O1UNSPpA=,tag:Go7NE8cAvJZLovBkRbmxwQ==,type:str]
    username: ENC[AES256_GCM,data:uKUHNV23dNga,iv:6BPUQKN/FqnYgPa0ihbTepshEPCE3DpubwH2TJY6hNI=,tag:KVYQOgrKf1Ne/ZG0Dau3/g==,type:str]
    database: ENC[AES256_GCM,data:9IXCx1dafeGA,iv:r37KJ86KO8oVxy25+MB6hwEjJBDEOV2FGYxdSk7BFJI=,tag:ruoHdcY/qB1mfnrZJJ8RKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zyvuxrlhky33w6k5e44unc9gpng629rrq3jd8rg427gvcyshpeysxcvdnq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxc0E3SWhaRUpDYWs2Vm9t
            SGdIdWY3ZGZINUt6Zmp6Q0Z5Zk0veHp4eTJBCnNSaGxSWEp2WXpBWFBUM1dNanpp
            TStmazN2WDNpMUtib3V2b0l3SEVoY0UKLS0tIEZ0T2tOZEFTaHIzdUVpbnFEMDFk
            bmZNcnkzUVBkQUxFOVJLZ1djQWtvancK5G9Rtn7/oICAoxFDBBwGIMZCeLlDlB9a
            R0wZz3o0zo8lLOyzWSByGmk8hXdRShhZtP5mfBplOgB21ulMSRvmNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-22T06:45:03Z"
    mac: ENC[AES256_GCM,data:bavNVCHubCqwDGvaZHjuORGrhb4fmZbAJ2L5fILOl1Lvhk+CNpTgRM5JiZZmbhwIc/8Ozm0cfEekMwn47ONytsuWBjPKQSQYthizAYWpf/ISUPp2ijlxLxosQ7UmApqs2xugcCgbLb/Gk57ocAJXMif3XT+nvN0T59sld0RC0+Y=,iv:/AlLKGEVSkVmfFLBqMWJRdwI83Jn9nR9wyhZUhWABHs=,tag:ofd3lh1u4HhRFXIURcF1vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
