controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/qbittorrent
          tag: 4.6.2
            # -- environment variables.
            # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
        env:
          TZ: Asia/Riyadh
          QBT_Preferences__WebUI__LocalHostAuth: false
          QBT_Preferences__WebUI__Password_PBKDF2: "@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
          QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
          QBT_Preferences__WebUI__AuthSubnetWhitelist: |-
              0.0.0.0/0
# -- Configures service settings for the chart.
service:
  main:
    controller: main
    ports:
      http:
        port: 8080


ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: true
    hosts:
      - host:  qbt.aksine.lcl
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http


# -- Configure persistence settings for the chart under this key.
persistence:
  config:
    enabled: true
    existingClaim: qbt-cfg-pvc
  downloads:
    enabled: true
    existingClaim: qbt-dl-pvc
    globalMounts:
      - path: /downloads