apiVersion: v1
data:
    adminID: ENC[AES256_GCM,data:rKEvk8dJPYY=,iv:B1+n9s912EWgSF2MQSeRV4CQHtUCl1T61tWHkGhOrRk=,tag:f4hZLlEs8uJuPx4QL5AmCQ==,type:str]
    adminKey: ENC[AES256_GCM,data:r/uZBR4Q6VPiITRrYlQ5Ux8jrXSZwgOaZySKz+ZE0RkkKXveCZWQ1fT6Xao7tvk6lATXnTMGlB4=,iv:pCkRkFG/A/6B5aJmm4EeqzOzJ2IhDWUPQP1jXgTKW6M=,tag:hpgATxuAaLg7/5XMbl+UNg==,type:str]
    userID: ENC[AES256_GCM,data:sLXOgEu5+9Y=,iv:q53Uuxu1N0pIK0PymqhU9ZMFp0RP0knG39wrZYS0IGU=,tag:2KIvaU03y4kclh3ZhWisYA==,type:str]
    userKey: ENC[AES256_GCM,data:wMS8RU13UYU9djpC7NaCWs0VVfNnrBd3pfjWu+I5/28CpYKGNDKwuNH8m1G0oeuH0NzLyUi5IQo=,iv:wQDs/MAnsCKnvFn0Dv1EjdEjllvW8PweLx/wCz0B3t8=,tag:dNCQomMQhfTFugx+wUvKcw==,type:str]
kind: Secret
metadata:
    name: csi-cephfs-secret
    namespace: ceph-csi-cephfs
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zyvuxrlhky33w6k5e44unc9gpng629rrq3jd8rg427gvcyshpeysxcvdnq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYnRIZ3BqUjAxdFBNeWRC
            UERqR3FTbFhmcEI5RllXRDJ5Q2ZMZ0xDK1h3CnJYK1Z6M0FrUzJpblVVcytHVlhl
            WC9Zc3JXdWhmR0lJOXBRajZ4RjdXVHcKLS0tIDNVTzE4cnE2bm9tb1Y1K2xVeU1S
            Y1UyYkNjSUdaRTlDS3JKeW5zeFVMVHMK9r4nwSlrDUZjfq2JXQd43AosDiEcjm82
            9uOFox/4ej+rHJs8Xa/tm7o2AeGqIiG3q0FhEShf+3fkhK7jo8eIZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-26T03:36:47Z"
    mac: ENC[AES256_GCM,data:qnX34ybvUFb3n5wW7TQwizeDCxWcrTdY6iKZW1Xr5Ii64RybS3FF8KLKh0LQifv21xJXAsHdpSnL2EuOcFXlz5qrWF8kcMOcCd5seoZVUHtKdNijc4gfeESXZwdjrv10FMF6glL/tjWncDKsUNoEwKiKioNpoBDek0ZmuPWyMGo=,iv:TQS+yE+JXa8Dpigjtp09NxihBkrpBsuNRFQVHUBn54Q=,tag:g6x3/wZoEA/u2cJIW/0J3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
