#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/plankanban/planka
  # -- image tag
  tag: "latest"
  # -- image pull policy
  pullPolicy: IfNotPresent
   
# -- environment variables. See [image repo](https://github.com/Tzahi12345/YoutubeDL-Material) for more details.
# @default -- See below

command:
- /bin/bash
- -c
- |
  for i in `seq 1 30`; do
  ./start.sh &&
  s=$? && break || s=$?;
  echo "Tried $i times. Waiting 5 seconds...";
  sleep 5;
  done; (exit $s)









env:
  BASE_URL: https://chart.local
  DATABASE_URL: postgresql://postgres@planka-postgresql/planka
  SECRET_KEY: notsecretkey
  TRUST_PROXY: 1
# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 1337


ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
   
postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 14
  primary:
    persistence:
      enabled: false
    extraEnvVars:
    - name: POSTGRES_DB
      value: planka
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
    pgHbaConfiguration: host all all all trust