
controllers:
  main:
    containers:
      main:
        image:
          pullPolicy: IfNotPresent
          repository: alfg/nginx-rtmp
          tag: latest

configMaps:
  conf:
    data:
      nginx.conf.template : |-
        daemon off;

        error_log /dev/stdout info;

        events {
            worker_connections 1024;
        }

          rtmp {
            server {
                    listen 1935;
                    chunk_size 4096;
                
                    allow publish all;
                  
                    # deny publish all;

            application TV {
                    live on;
                    record off;
                            }
                    }
                  }


        http {
            access_log /dev/stdout combined;

            ssl_ciphers         HIGH:!aNULL:!MD5;
            ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
            ssl_session_cache   shared:SSL:10m;
            ssl_session_timeout 10m;

            server {
                listen 8080;

                # Uncomment these lines to enable SSL.
                # Update the ssl paths with your own certificate and private key.
                # listen 443 ssl;
                # ssl_certificate     /opt/certs/example.com.crt;
                # ssl_certificate_key /opt/certs/example.com.key;

                

            

              location /stat {
                  rtmp_stat all;
                  rtmp_stat_stylesheet /stat.xsl;
              }
              location /stat.xsl {
                root /www/static;
              }


              location = /crossdomain.xml {
                    root /www/static;
                    default_type text/xml;
                    expires 24h;
              }

            }
        }
service:
  main:
    controller: main
    ports:
      http:
        port: 8080
  rtmp:
    controller: main
    loadBalancerIP: 10.0.0.75
    enabled: true
    type: LoadBalancer
    ports:
      rtmp:
        port: 1935

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: true
    hosts:
      - host:  rtmpstat.aksine.lcl
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http

persistence:
  config:
    enabled: true
    type: configMap
    name: rtmp-conf
    advancedMounts:
      main:
        main:
          - path: /etc/nginx/nginx.conf.template
            subPath: nginx.conf.template

