controllers:
  main:
    containers:
      main:
        image:
          repository: docker.io/flcontainers/guacamole
          tag: 1.5.4
            # -- environment variables.
            # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
        env:
          # -- Set the container timezone
          TZ: Asia/Riyadh
          EXTENSIONS: auth-duo

        lifecycle:
          postStart:
            exec:
              command: ["sh", "-c", "cp -v /tmp/guacamole.properties /config/guacamole/guacamole.properties && chmod -R 777 /config/guacamole "]
              #command: ["sh", "-c", "sleep 220 && mkdir -p /config/guacamole/ && cp -v /tmp/guacamole.properties /config/guacamole/guacamole.properties && chmod -R 777 /config/guacamole && ps | grep tom | grep -v grep  | awk '{print $1}' | xargs kill -9"]


        probes:
          # -- Liveness probe configuration
          # @default -- See below
          liveness:
            # -- Enable the liveness probe
            enabled: false
          readiness:
            # -- Enable the readiness probe
            enabled: false
          startup:
            # -- Enable the startup probe
            enabled: false
service:
  main:
    controller: main
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: true
    hosts:
      - host: guac.aksine.lcl
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http


# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    existingClaim: guac-pvc

  # configadd:
  #   enabled: true
  #   type: secret
  #   name: guac-secret
  #   globalMounts:
  #     - path: /config/guacamole/guacamole.properties
  #       subPath: guacamole.properties
  configadd:
    enabled: true
    type: secret
    name: guac-secret
    globalMounts:
      - path: /tmp/guacamole.properties
        subPath: guacamole.properties