---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aksine-am-com

  namespace: default
spec:
  secretName: aksine-am-com-tls
  additionalOutputFormats:
  - type: CombinedPEM
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.aksine-am.com"
  dnsNames:
  - "aksine-am.com"
  - "*.aksine-am.com"
