## Default values for Cloudflared

## @section Image parameters

## @param image.repository The Docker repository to pull the image from.
## @param image.tag The image tag to use.
## @param image.imagePullPolicy The logic of image pulling.
##
image:
  repository: cloudflare/cloudflared
  tag: "2022.10.3"
  imagePullPolicy: IfNotPresent

## @section Deployment parameters

## @param replicaCount The number of replicas to deploy.
##
replicaCount: 3
## @param tunnelID The Argo Tunnel ID you created. Check the configuration section for details.
##
tunnelID: "ae2f2a10-6648-476a-838f-5367c06e06ec"
## @param auth.accountTag The Argo tunnel account tag.
## @param auth.tunnelName The Argo tunnel name.
## @param auth.tunnelSecret The Argo tunnel secret.
##
auth:
  accountTag: "b2586fefc13a419af1a2246f59f6c390"
  tunnelName: "aksine-am"
  tunnelSecret: "rUflM3RO7WVRuipwG1kzJM5ptXXBawOVFaiMwb3MnMw="
## @param existingSecret The name of an existing secret containing the Argo tunnel settings.
##
existingSecret: ""
## @param warpRouting Whether to enable WARP traffic routing to local subnets.
##
warpRouting: false
## @param ingress The ingress settings to apply. Check the configuration section for examples.
##
ingress:
  - hostname: aksine-am.com
    service: https://10.0.0.109:443
    originRequest:
      originServerName: www.notesignwave.duckdns.org
  - hostname: guaccf.aksine-am.com
    service: http://10.0.0.102:8080
  - hostname: notes.aksine-am.com
    service: http://notes.aksine.lcl
    path: /api/*
    originRequest:
      originServerName: notes.aksine.lcl
      httpHostHeader: notes.aksine.lcl
  - service: http_status:404