---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-fanart-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: immich-fanart-pv
  storageClassName: smb
