---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-phone-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1001
    - gid=1001
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    readOnly: true
    volumeHandle: immich-phone-pv # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//nas.aksine.lcl/Share/Phone_Sync"
    nodeStageSecretRef:
      name: smb-creds
      namespace: default
