{{- if not .Values.nginxConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-rtmp.fullname" . }}-config
  labels:
    {{- include "nginx-rtmp.labels" . | nindent 4 }}
data:
  nginx.conf.template: {{ toYaml .Values.nginxConfig | indent 4 }}
{{- end }}
