#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

controllers:
  main:
    containers:
      main:
        image:
          repository: alexta69/metube
          tag: latest


image:
  # -- image repository
  repository: alexta69/metube
  # -- image tag
  tag: "latest"
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [image repo](https://github.com/Tzahi12345/YoutubeDL-Material) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: Asia/Qatar
  # -- Specify the user ID the application will run as
  UID: "1000"
  # -- Specify the group ID the application will run as
  GID: "1000"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8081

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  downloads:
    enabled: true
    mountPath: /downloads
    type: pvc

