---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbt-dl-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  # volumeName should be same as PV name
  volumeName: qbt-dl-pv
  storageClassName: smb