---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: yt-dl-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: yt-dl-pv
  storageClassName: smb
