---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: music-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: music-pv
  storageClassName: smb
